# Leaving unnecessary do because
#  * they improve readability
#  * if you add a context, or an it, it'll still compile, without remembering that there was no do
#  before because at the time there was a single function inside
#  * without those do, ormolu does some formatting that looks crazy to me
- ignore: {name: "Redundant do"}
