version: 2

jobs:
  nix:
    docker:
      - image: nixos/nix:latest
    working_directory: ~/krank
    steps:
      - checkout
      - restore_cache:
          keys:
            - cci-nix-v2-{{ checksum "nixpkgs.nix" }}-{{ checksum "default.nix" }}-{{ checksum "krank.cabal" }}
            - cci-nix-v2-{{ checksum "nixpkgs.nix" }}-{{ checksum "default.nix" }}
            - cci-nix-v2-{{ checksum "nixpkgs.nix" }}
            - cci-nix-v2
      - run:
          name: Check hlint
          command: nix-build -A hlint
      - run:
          name: Build current GHC (8.8)
          command: nix-build -A krank
      - run:
          name: Build GHC 8.6
          command: nix-build -A krank_86
      - run:
          name: Check ormolu
          command: nix-build -A ormolu
      - save_cache:
          when: always
          name: Cache Dependencies
          key: cci-nix-v2-{{ checksum "nixpkgs.nix" }}-{{ checksum "default.nix" }}-{{ checksum "krank.cabal" }}
          paths:
            - "/nix/store"


  stack:
    docker:
      - image: fpco/stack-build:lts
    working_directory: ~/krank
    steps:
      - checkout
      - run:
         name: Install dependencies
         command: apt-get update && apt-get install -y libpcre2-dev
      - restore_cache:
          keys:
            - cci-stack-v2-{{ checksum "stack.yaml" }}-{{ checksum "krank.cabal" }}
            - cci-stack-v2-{{ checksum "stack.yaml" }}
            - cci-stack-v2
      - run:
          name: Build 8.8
          command: stack test -j1
      - run:
          name: Build 8.6
          command: stack --resolver lts-14.27 test -j1
      - save_cache:
          when: always
          name: Cache Dependencies
          key: cci-stack-v2-{{ checksum "stack.yaml" }}-{{ checksum "krank.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

workflows:
  version: 2
  nix_stack:
    jobs:
      - nix
      - stack
